config/routes.rb
Zomato::Application.routes.draw do
  get "reviews/add"
  get "ratings/add"
  get "restaurants/index"

  root 'browser#index'
  get ':country_name' => 'browser#list_cities', as: :list_cities
  get ':country_name/:city_name' => 'browser#list_restaurants', as: :list_restaurants

  get ':country_name/:city_name/restaurants/:id' => 'restaurants#show', as: :restaurant
  post 'restaurants/:id/rating' => 'ratings#add', as: :restaurant_rating
  post 'restaurants/:id/review' => 'reviews#add', as: :restaurant_review

  

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :country, :counter_cache => true
  has_many :restaurants
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :restaurant, :counter_cache => true
  belongs_to :review
  validates :restaurant_id, presence: true
  validates :value, presence: true, :numericality => { :greater_than_or_equal_to => 10, :less_than_or_equal_to => 50 }
  after_create :recalculate_average

  private

  def recalculate_average
    self.restaurant.recalculate_average
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :city, :counter_cache => true
  has_many :ratings
  has_many :reviews

  def get_average_rating
    self.average_rating.to_f/10
  end

  def get_cost
    self.cost.to_f/100
  end

  def recalculate_average
    self.average_rating = (self.ratings.sum(:value).to_f/self.ratings.length).to_i
    self.save!
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant, :counter_cache => true
  has_many :ratings
  validates :reviewer, presence: true
  validates :review_text, presence: true
  def get_rating
    self.ratings.first.value.to_f/10
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/browser_controller.rb
class BrowserController < ApplicationController
  before_filter :set_country, except: [:index]
  def index
    @countries = Country.all
  end

  def list_cities
    @cities = @country.cities
  end

  def list_restaurants
    @city = @country.cities.where(name: params[:city_name]).first
    @restaurants = @city.restaurants
  end

  private

  def set_country
    @country = Country.find_by_name(params[:country_name])
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def add
    restaurant = Restaurant.find(params[:id])
    restaurant.ratings.create(params.require(:rating).permit(:value))

    redirect_to restaurant_path(params[:country_name], params[:city_name],params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def show
    @restaurant = Restaurant.find(params[:id])
    @country = Country.find_by_name(params[:country_name])
    @city = @country.cities.where(name: params[:city_name]).first
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def add
    restaurant = Restaurant.find(params[:id])
    review = restaurant.reviews.create(params.require(:review).permit(:reviewer, :review_text))

    if review.errors.messages.empty?
      restaurant.ratings.create(params.require(:review).permit(:value).merge(review_id: review.id))
    else
      flash[:error] = 'All fields are mandatory'
    end
    redirect_to restaurant_path(params[:country_name], params[:city_name],params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/browser_helper.rb
module BrowserHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def show_rating(restaurant)
    if restaurant.get_average_rating > 0
      "#{restaurant.get_average_rating}/5 ( #{restaurant.ratings_count} votes)"
    else
     'Not yet rated'
    end
  end

  def ratings_options
    [["1.0", 10], ["1.5", 15], ["2.0", 20], ["2.5", 25], ["3.0", 30], ["3.5", 35], ["4.0", 40], ["4.5", 45], ["5.0",50]]
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/browser/index.html.erb
<p>Select a Country: </p>
<%=render :partial => 'countries/index'%>

app/views/browser/list_cities.html.erb
<%=link_to 'All Countries', root_path %> | <%=@country.name %> <br />

<p>Select your city:</p>

<%= render :partial => 'cities/index' %>

app/views/browser/list_restaurants.html.erb
<%=link_to 'All Countries', root_path %> | <%=link_to @country.name, list_cities_path(@country.name) %> | <%= @city.name %>
<br />

<p>Browse Restaurants in <%= @city.name %>:</p>

<%= render :partial => 'restaurants/index' %>

app/views/cities/_index.html.erb
<% if @cities.length > 0 %>
    <% @cities.each do |city| %>
        <%=link_to city.name, list_restaurants_path(@country.name,city.name) %> - (<%=city.restaurants_count %>)
        <br />
    <% end %>
<% else %>
    No Cities Listed
<% end %>

app/views/countries/_index.html.erb
<% if @countries.length > 0 %>
    <% @countries.each do |country| %>
        <%=link_to country.name, list_cities_path(country.name) %>
        <br />
    <% end %>
<% else %>
    No Countries in Database, please seed the database using rake db:seed
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zomato - Restaurants in your city.</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Welcome to Zomato, Browse Restaurants in Your Location</h1>
<%= yield %>

</body>
</html>

app/views/ratings/add.html.erb
<h1>Ratings#add</h1>
<p>Find me in app/views/ratings/add.html.erb</p>

app/views/restaurants/_index.html.erb
<% if @restaurants.length > 0 %>
<% @restaurants.each do |restaurant| %>
    <p>
    <%=link_to restaurant.name, restaurant_path(@country.name, @city.name,restaurant.id) %> -  <%= show_rating(restaurant) %> - <%=restaurant.reviews_count %> reviews
    <br />
    Address: <%=restaurant.address %> <br />
    Cost for 2: Rs. <%=restaurant.get_cost %>
    </p>
<% end %>
<% else %>
    No Restaurants Listed in this City.
<% end %>

app/views/restaurants/show.html.erb
<%=link_to 'All Countries', root_path %> | <%=link_to @country.name, list_cities_path(@country.name) %> | <%= link_to @city.name, list_restaurants_path(@country.name, @city.name) %> | <%= @restaurant.name %>
<br />
<h1><%=@restaurant.name %></h1>
<h4>Address: <%=@restaurant.address %></h4>
<h4>Cuisines: <%=@restaurant.cuisines %></h4>
<p>
  Rating: <%= show_rating(@restaurant)  %>
  <%= form_for(:rating, url: restaurant_rating_path(@restaurant)) do |f| %>
    <p>
      <%= f.select :value, options_for_select(ratings_options) %>

        <%= hidden_field_tag 'country_name', @country.name %>
        <%= hidden_field_tag 'city_name', @city.name %>

      <%= f.submit 'Rate' %>
    </p>
  <% end %>
</p>
<h5> Cost for 2: Rs. <%=@restaurant.get_cost %></h5>
<h4>Add a Review:</h4>
<%= flash[:error] %>
    <%= form_for(:review, url: restaurant_review_path(@restaurant)) do |f| %>
      <p> Name: <%= f.text_field :reviewer %></p>
      <p> Rating: <%= f.select :value, options_for_select(ratings_options) %></p>
      <p> Review: </p>
      <p> <%= f.text_area :review_text %></p>

        <%= hidden_field_tag 'country_name', @country.name %>
        <%= hidden_field_tag 'city_name', @city.name %>

    <%= f.submit 'Submit Review' %>

    <% end %>
<h4><%= @restaurant.reviews_count == 0? "No Reviews Yet!": "Reviews(#{@restaurant.reviews_count}):" %></h4>
<% @restaurant.reviews.order('reviews.created_at DESC').each do |review| %>
    <p>
      Reviewer Name: <%=review.reviewer %> - Rated <%=review.get_rating %> / 5 <br />
      <%= review.review_text %>
    </p>
<% end %>

app/views/reviews/add.html.erb
<h1>Reviews#add</h1>
<p>Find me in app/views/reviews/add.html.erb</p>